package email

import (
	"crypto/ecdsa"
	"crypto/sha256"
	"crypto/x509"
	"encoding/base64"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"log/slog"
	"strings"
	"time"

	"github.com/Marc3usz/DoYouSend/backend/internal/providers"
)

// ErrInvalidWebhookSignature is returned when the ECDSA signature does not match.
var ErrInvalidWebhookSignature = errors.New("invalid SendGrid webhook signature")

// sendgridEvent mirrors the JSON structure sent by SendGrid Event Webhook.
// See: https://docs.sendgrid.com/for-developers/tracking-events/event
type sendgridEvent struct {
	Email       string `json:"email"`
	Timestamp   int64  `json:"timestamp"`
	Event       string `json:"event"`
	SGMessageID string `json:"sg_message_id"`
	Reason      string `json:"reason"`
	Response    string `json:"response"`
	Status      string `json:"status"`
}

// VerifySendGridWebhookSignature verifies the ECDSA SHA-256 signature generated by
// SendGrid Signed Event Webhook (ADR-0008).
//
// Parameters:
//   - publicKeyBase64: base64-encoded ECDSA public key from SendGrid (SENDGRID_WEBHOOK_PUBLIC_KEY)
//   - payload: raw HTTP request body bytes
//   - signatureBase64: value of header X-Twilio-Email-Event-Webhook-Signature
//   - timestamp: value of header X-Twilio-Email-Event-Webhook-Timestamp
func VerifySendGridWebhookSignature(publicKeyBase64 string, payload []byte, signatureBase64, timestamp string) error {
	if strings.TrimSpace(publicKeyBase64) == "" {
		return fmt.Errorf("%w: public key is empty", ErrInvalidWebhookSignature)
	}
	if strings.TrimSpace(signatureBase64) == "" || strings.TrimSpace(timestamp) == "" {
		return fmt.Errorf("%w: signature or timestamp header is missing", ErrInvalidWebhookSignature)
	}

	der, err := base64.StdEncoding.DecodeString(strings.TrimSpace(publicKeyBase64))
	if err != nil {
		return fmt.Errorf("%w: decode public key base64: %v", ErrInvalidWebhookSignature, err)
	}

	pub, err := x509.ParsePKIXPublicKey(der)
	if err != nil {
		return fmt.Errorf("%w: parse public key: %v", ErrInvalidWebhookSignature, err)
	}

	ecdsaPub, ok := pub.(*ecdsa.PublicKey)
	if !ok {
		return fmt.Errorf("%w: public key is not ECDSA", ErrInvalidWebhookSignature)
	}

	sig, err := base64.StdEncoding.DecodeString(strings.TrimSpace(signatureBase64))
	if err != nil {
		return fmt.Errorf("%w: decode signature base64: %v", ErrInvalidWebhookSignature, err)
	}

	h := sha256.New()
	h.Write([]byte(timestamp))
	h.Write(payload)
	digest := h.Sum(nil)

	if !ecdsa.VerifyASN1(ecdsaPub, digest, sig) {
		return ErrInvalidWebhookSignature
	}

	return nil
}

// ParseSendGridEvents parses an HTTP request body containing a JSON array of SendGrid
// webhook events into canonical DeliveryReport structs (ADR-0008).
//
// Event mapping:
//   - "delivered"             → StatusDelivered
//   - "bounce", "dropped"     → StatusFailed (reason stored in ErrorMessage)
//   - "processed", "deferred" → StatusSent
//   - "open", "click", "spamreport", "unsubscribe" and unrecognised events
//     are engagement or informational events, not delivery statuses, and are ignored.
//
// ProviderMessageID is extracted from sg_message_id by taking the part before the
// first dot (which matches the X-Message-Id header returned by POST /v3/mail/send).
//
// An actionable event missing sg_message_id is skipped (not fatal for the batch),
// so that one malformed event does not cause loss of the remaining valid reports.
// SendGrid sends many events in a single POST; rejecting the whole batch would
// trigger infinite retries.
//
// The consumer (delivery worker) is responsible for applying reports in forward-only
// order: a report with StatusSent must not overwrite StatusDelivered. The parser
// emits every actionable event and does not enforce ordering (ADR-0008).
//
// Returns ErrMalformedReport only if the JSON itself is invalid (not an array, etc.).
func ParseSendGridEvents(body io.Reader, logger *slog.Logger) ([]providers.DeliveryReport, error) {
	if logger == nil {
		logger = slog.Default()
	}

	var events []sendgridEvent
	if err := json.NewDecoder(body).Decode(&events); err != nil {
		return nil, fmt.Errorf("%w: invalid SendGrid events JSON: %w", providers.ErrMalformedReport, err)
	}

	var reports []providers.DeliveryReport
	for i, e := range events {
		status, isActionable := mapSendGridEvent(e.Event)
		if !isActionable {
			// Engagement/informational events (open, click, unsubscribe, spamreport)
			// do not update delivery status.
			continue
		}

		rawID := strings.TrimSpace(e.SGMessageID)
		if rawID == "" {
			// Skip instead of failing the whole batch (review comment 4).
			// Log the index and event type but never the recipient e-mail.
			logger.Warn("sendgrid event without sg_message_id, skipping",
				"event_index", i,
				"event_type", e.Event,
			)
			continue
		}

		// SendGrid sg_message_id format: "<x-message-id>.<filter-info>".
		// Extract prefix before first dot to match X-Message-Id.
		msgID := rawID
		if idx := strings.IndexByte(rawID, '.'); idx != -1 {
			msgID = rawID[:idx]
		}

		var ts time.Time
		if e.Timestamp > 0 {
			ts = time.Unix(e.Timestamp, 0).UTC()
		}

		var errMsg string
		if status == providers.StatusFailed {
			errMsg = formatFailureReason(e)
		}

		reports = append(reports, providers.DeliveryReport{
			ProviderMessageID: msgID,
			Channel:           providers.ChannelEmail,
			Status:            status,
			ErrorMessage:      errMsg,
			Timestamp:         ts,
		})
	}

	return reports, nil
}

func mapSendGridEvent(event string) (providers.DeliveryStatus, bool) {
	switch strings.ToLower(event) {
	case "delivered":
		return providers.StatusDelivered, true
	case "bounce", "dropped":
		return providers.StatusFailed, true
	case "processed", "deferred":
		return providers.StatusSent, true
	default:
		// open, click, spamreport, unsubscribe, group_unsubscribe, group_resubscribe, unknown
		return "", false
	}
}

func formatFailureReason(e sendgridEvent) string {
	reason := strings.TrimSpace(e.Reason)
	response := strings.TrimSpace(e.Response)

	if reason != "" && response != "" {
		return fmt.Sprintf("%s (%s)", reason, response)
	}
	if reason != "" {
		return reason
	}
	if response != "" {
		return response
	}
	return fmt.Sprintf("email %s by SendGrid", e.Event)
}
